<?php

namespace ApiRestBundle\Entity;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{
    public function remove($id)
    {
        $conn = $this->_em->getConnection();
        $sql = 'DELETE FROM Article WHERE slug = :id;';
        $statement = $conn->executeQuery($sql, array('id' => $id));
        $article = $this->_em->getReference('ApiRestBundle:Article', $id);
        $result = $statement->rowCount();
        return $result;
    }

    public function clearAllArticles()
    {
        $conn = $this->_em->getConnection();
        $sql = 'DELETE FROM Article;';
        $statement = $conn->executeQuery($sql);
        $result = $statement->rowCount();
        return $result;
    }
}
